-- XMECO Database Migration V003
-- 完整建表脚本（含所有字段更新）

CREATE TABLE IF NOT EXISTS agent (id SERIAL PRIMARY KEY, name VARCHAR(200) NOT NULL, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS project (id SERIAL PRIMARY KEY, name VARCHAR(200) NOT NULL, agent_id INT REFERENCES agent(id), address VARCHAR(500), admin_code VARCHAR(20), created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS building (id SERIAL PRIMARY KEY, project_id INT NOT NULL REFERENCES project(id), name VARCHAR(200) NOT NULL, outdoor_temp DECIMAL(5,1), outdoor_humidity DECIMAL(5,1), total_energy DECIMAL(12,2) DEFAULT 0, save_rate DECIMAL(5,3) DEFAULT 0, save_energy DECIMAL(12,2) DEFAULT 0, carbon_rate DECIMAL(5,3) DEFAULT 0, carbon_saving DECIMAL(12,2) DEFAULT 0, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS device (id SERIAL PRIMARY KEY, building_id INT NOT NULL REFERENCES building(id), name VARCHAR(200) NOT NULL, device_type VARCHAR(50) NOT NULL, gateway_imei VARCHAR(20), gateway_type VARCHAR(20) DEFAULT 'custom', node_address INT DEFAULT 0, device_no INT DEFAULT 1, ct_ratio INT DEFAULT 1, pt_ratio INT DEFAULT 1, rated_voltage DECIMAL(8,1), rated_current DECIMAL(8,1), online_status VARCHAR(20) DEFAULT '在线', device_status VARCHAR(50) DEFAULT '开机', last_record_at TIMESTAMPTZ, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS device_properties (id SERIAL PRIMARY KEY, device_id INT NOT NULL REFERENCES device(id), prop_name VARCHAR(100) NOT NULL, prop_short VARCHAR(50), prop_value VARCHAR(100), unit VARCHAR(20), operation_type VARCHAR(50), is_key BOOLEAN DEFAULT false, prop_type VARCHAR(50), min_value VARCHAR(50), max_value VARCHAR(50), sort_order INT DEFAULT 0);
CREATE TABLE IF NOT EXISTS register (id SERIAL PRIMARY KEY, property_id INT NOT NULL REFERENCES device_properties(id), name VARCHAR(100), read_addr INT NOT NULL, read_code VARCHAR(5) DEFAULT '03', write_addr INT, write_code VARCHAR(5), command_name VARCHAR(100), command_code VARCHAR(50), status_code VARCHAR(50), data_type VARCHAR(20) DEFAULT '无符号16位整数', data_length INT DEFAULT 1, data_order VARCHAR(10) DEFAULT '高位在前', data_mask VARCHAR(20), magnification DECIMAL(10,2) DEFAULT 1);

CREATE TABLE IF NOT EXISTS users (id SERIAL PRIMARY KEY, username VARCHAR(100) UNIQUE NOT NULL, password_hash VARCHAR(255) NOT NULL, agent_id INT REFERENCES agent(id), role_id INT, default_project_id INT, remark VARCHAR(500), openid VARCHAR(100), alarm_channels JSONB DEFAULT '[]', is_active BOOLEAN DEFAULT true, last_login_at TIMESTAMPTZ, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS role (id SERIAL PRIMARY KEY, code VARCHAR(30) UNIQUE NOT NULL, name VARCHAR(50) NOT NULL, level SMALLINT NOT NULL DEFAULT 0, description VARCHAR(200), is_system BOOLEAN DEFAULT false);
CREATE TABLE IF NOT EXISTS permission (id SERIAL PRIMARY KEY, code VARCHAR(50) UNIQUE NOT NULL, name VARCHAR(50) NOT NULL, perm_group VARCHAR(30) NOT NULL);
CREATE TABLE IF NOT EXISTS role_permission (role_id INT NOT NULL REFERENCES role(id), perm_id INT NOT NULL REFERENCES permission(id), PRIMARY KEY (role_id, perm_id));

CREATE TABLE IF NOT EXISTS alarm_rule (id SERIAL PRIMARY KEY, name VARCHAR(100), device_id INT REFERENCES device(id), property_id INT REFERENCES device_properties(id), project_id INT REFERENCES project(id), device_type VARCHAR(50), metric VARCHAR(50), condition VARCHAR(20), threshold DECIMAL(10,3), target_value VARCHAR(100), min_value VARCHAR(50), max_value VARCHAR(50), level VARCHAR(10) DEFAULT 'warning', notify_users JSONB DEFAULT '[]', enabled BOOLEAN DEFAULT true);
CREATE TABLE IF NOT EXISTS alarm_log (id SERIAL PRIMARY KEY, project_id INT, device_id INT, device_name VARCHAR(200), alarm_type VARCHAR(50), level VARCHAR(10), message TEXT, value VARCHAR(100), threshold VARCHAR(100), ack_by VARCHAR(100), ack_at TIMESTAMPTZ, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS control_record (id SERIAL PRIMARY KEY, project_name VARCHAR(200), building_name VARCHAR(200), device_name VARCHAR(200), prop_name VARCHAR(100), control_value VARCHAR(100), username VARCHAR(100), user_remark VARCHAR(200), snapshot_before JSONB, snapshot_after JSONB, created_at TIMESTAMPTZ DEFAULT NOW());

CREATE TABLE IF NOT EXISTS startup_plan (id SERIAL PRIMARY KEY, name VARCHAR(100) NOT NULL, building_id INT NOT NULL REFERENCES building(id), plan_type VARCHAR(20) DEFAULT 'startup', precheck_online BOOLEAN DEFAULT true, precheck_alarm BOOLEAN DEFAULT true, enabled BOOLEAN DEFAULT true, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS startup_step (id SERIAL PRIMARY KEY, plan_id INT NOT NULL REFERENCES startup_plan(id) ON DELETE CASCADE, sort_order INT NOT NULL DEFAULT 0, device_id INT NOT NULL REFERENCES device(id), property_id INT NOT NULL DEFAULT 0, action VARCHAR(50) NOT NULL, target_value VARCHAR(50), wait_seconds INT NOT NULL DEFAULT 30, UNIQUE (plan_id, sort_order));
CREATE TABLE IF NOT EXISTS startup_execution (id SERIAL PRIMARY KEY, plan_id INT NOT NULL, plan_name VARCHAR(100), triggered_by VARCHAR(100), trigger_from VARCHAR(50), status VARCHAR(20) DEFAULT 'running', total_steps INT, done_steps INT DEFAULT 0, error_step INT, error_message TEXT, started_at TIMESTAMPTZ DEFAULT NOW(), finished_at TIMESTAMPTZ);

CREATE TABLE IF NOT EXISTS device_telemetry (ts TIMESTAMPTZ NOT NULL, device_id INT NOT NULL, metric TEXT NOT NULL, value DOUBLE PRECISION, unit TEXT);
SELECT create_hypertable('device_telemetry', 'ts', if_not_exists => true);
CREATE TABLE IF NOT EXISTS dashboard_config (key VARCHAR(50) PRIMARY KEY, value TEXT, updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS gateway_config (gateway_mac VARCHAR(20) PRIMARY KEY, gateway_type VARCHAR(20) NOT NULL DEFAULT 'custom', dtu_model VARCHAR(50), dtu_ip_expected VARCHAR(45), remark VARCHAR(500));
